# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: JEEON BAE
title: Curriculum Vitae
email: jeeon98b@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BAE-JEEON
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# # xing_username: jekyll
# # pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# # - title: another link
# #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
# #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Je-Eon Bae and I am undergraduate student at Kyung Hee University. My goal is to make deep learning technology more accessible and allow individuals from diverse backgrounds to benefit from its potential.
  
  Currently, my research is focused on two specific areas: <mark>Semi-supervised Learning</mark> and <mark>Self-supervised Learning</mark>. I am interested in improving the trade-off between the cost of training and model performance in these areas, which can help to make deep learning more accessible to humans.

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ML Lab
        link: https://ml.postech.ac.kr/
        # link_text: https://ml.postech.ac.kr/
        sub_title: Undergraduate Lab Intern
        caption: January 2023 - Present
#         quote: >
#           Pohang University of Science and Technology (POSTECH) is a private research university in Pohang, South Korea.
        description: | # this will include new lines to allow paragraphs
           Under the guidance of NamHoon Lee, I am currently interning at the Log (Lee Optimization Group), a machine learning laboratory located at POSTECH.   
#     content:
#       - layout: left
#         title: MLVC Lab
#         link: https://mlvc.khu.ac.kr/
#         # link_text: https://mlvc.khu.ac.kr/
#         sub_title: Undergraduate Lab Intern
#         caption: January 2022 - December 2022
# #         quote: >
# #            University of Kyung Hee is a private research university in Seoul and Yongin, South Korea.
#         description: | # this will include new lines to allow paragraphs
#            Under the guidance of SungHo Bae, I interned at the MLVC(Machine Learning Visual Computing Lab), located at Kyung Hee university.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kyung Hee University
        caption: 2017.03 - 2023.08
        sub_title: Industrial Engineering & Software Engineering
                   (4.22/4.5)
#         quote: >
#           University of Kyung Hee is a private research university in Seoul and Yongin, South Korea.
        description: | # this will include new lines to allow paragraphs
         As an undergraduate at Kyung Hee University, I pursued a major in Industrial Engineering, building a strong mathematical foundation in subjects that are crucial for understanding deep learning theory, including optimization, probability and statistics, and linear algebra. I also earned a degree in Software Engineering, which equipped me with the necessary skills to implement deep learning algorithms.

      
  - title: Honors and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 2020-1 Academic Excellence Award
      - 2021-2 Academic Excellence Award
      - KHU Data Analysis Competition 1th place 
      - 2022 Korea Software Conference Excellent Paper Award
      - 2022 Korea Computer Science Conference Excellent Paper Award
      - 2022 KHU Software Mileage Contest Gold Prize 
      - KHU AI Competition In-campus 4th place 
      - SK Startup Club Selection Contest Encouragement Award
      - KHU Software Startup Idea Contest Encouragement Award
      - 2022-1 KHU Scholarship for Outstanding Activities 
      - 2022-2 KHU Scholarship for Outstanding Activities 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
