# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeeon Bae
title: CV
email: jeeon98b@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BAE-JEEON
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# # xing_username: jekyll
# # pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google scholar
  icon: fas fa-globe
  url: https://scholar.google.co.kr/citations?user=Je-Eon%20Bae&user=44uv_u4AAAAJ
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Je-Eon Bae and I am undergraduate student at Kyung Hee University. My goal is to make deep learning technology more accessible and allow individuals from diverse backgrounds to benefit from its potential.
  
  Currently, my research is focused on two specific areas: <mark>Semi-,Self-supervised Learning</mark> and <mark>Model Compression</mark>. I am interested in improving the trade-off between the training cost and model performance in these areas, which can help to make deep learning more accessible to humans.

content:
#   - title: Projects # Title for the section
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ML Lab
        link: https://ml.postech.ac.kr/
        sub_title: Undergraduate Lab Intern
        caption: January 2023 - Present
        description: |
          Under the guidance of [Prof.Namhoon Lee](https://namhoonlee.github.io/), I am currently interning at the **Machine Learning Lab**, [POSTECH](https://www.postech.ac.kr/).

      - layout: left
        title: MLVC Lab
        link: https://mlvc.khu.ac.kr/
        sub_title: Undergraduate Lab Intern
        caption: January 2022 - December 2022
        description: |
          Under the guidance of [Prof.Sungho Bae](https://scholar.google.co.kr/citations?user=EULut5oAAAAJ&hl=ko), I interned at the **Machine Learning and Visual Computing Lab**, [Kyung Hee university](https://www.khu.ac.kr/).

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kyung Hee University
        caption: "March 2017 - August 2023"
        sub_title: "Industrial Engineering & Software Engineering (GPA: 4.22/4.5)"
        description: | # this will include new lines to allow paragraphs
         During my time as an undergraduate student at Kyung Hee University, I pursued a dual degree in [Industrial Engineering](https://eng.khu.ac.kr/ie) and [Software Engineering](https://software.khu.ac.kr/software/user/main/view.do). 
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Je-Eon Bae**, HyunDong Cho, ChanMi Park, SungHo Bae, WonHee Lee. Dataset Condensation with Gradient Matching Considering Model Biased Noise, KCC 2022. **Excellent Paper Award**
      
      - **Je-Eon Bae**, Sung-Ho Bae, Imbalance Loss with the Statistical Properties of Pseudo-labels in Class Imbalanced Semi-Supervised Learning, KSC 2022.
      
      - **Je-Eon Bae**, Sung-Ho Bae, Adaptive Regularization Loss for Improving Quality of Pseudo-label in Class Imbalanced Semi-Supervised Learning, KSC 2022. **Excellent Paper Award**
      
      - **Je-Eon Bae**, Dae-Ho Lee, Semi-Supervised Object Detection with Flexible EMA, KCC 2023.
      
      - **Je-Eon Bae**, Two-Stage Test Time Intervention for Korean OCR Models, KCC 2023

  - title: Honors and Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 2017 SK Startup Club Contest Encouragement Award
      - 2020 KHU Software Idea Contest Encouragement Award
      - 2020 KHU Academic Excellence Award
      - 2021 KHU Academic Excellence Award
      - 2022 KHU Data Analysis Competition 1th place 
      - 2022 Korea Software Conference Excellent Paper Award
      - 2022 Korea Computer Science Conference Excellent Paper Award
      - 2022 KHU Software Mileage Contest Gold Prize 
      - 2022 KHU AI Competition 4th place 
      - 2022-1 KHU Scholarship for Outstanding Activities 
      - 2022-2 KHU Scholarship for Outstanding Activities 
      
  - title: Patents
    layout: text
    content: | # this will include new lines to allow paragraphs
        - Applied for a patent for the alarm device, **ALARM DEVICE THAT DO NOT DISTURB OTHERS** on August 9, 2017.
      
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
